---
version: "2.1"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - PASSWORD=PASSWORD
    volumes:
      - ./config:/config
    ports:
      - 8084:80
    restart: unless-stopped
