---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /mnt/Torrent/Completed:/downloads
      - /mnt/Serier:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
