---
- name: Make sure group "docker" exists
  become: true
  group:
    name: docker
    state: present

- name: Add user to group "docker"
  become: true
  user:
    name: "{{ docker_user.name }}"
    group: docker