---
- hosts: 
  - proxmox-docker-tmp
  roles:
    #- role: geerlingguy.docker
    #  become: true
    ##  vars: 
    #    docker_package: "{{ 'docker-ce' if ansible_os_family == 'Debian' else 'docker' }}"
    #    docker_users:
    #      - "{{ user }}"
    - docker
    #- sickchill
    - couchpotato
    #- jenkins
