---

- name: Make sure user exists
  become: true
  user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"

- name: Create install directory
  file:
    path: /home/figge/containers/librespeed
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create config directory
  file:
    path: /home/figge/containers/librespeed/config
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/figge/containers/librespeed/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/local/bin/docker-compose -f %s config
  notify: restart librespeed
  become: true
